### PR TITLE
Game stats

### PR DESCRIPTION
**Pull request by naomiyocum**
was able to finish the last few methods of Game Statistics and the first method of League Statistics. Depending on the method, it can be helpful changing the game_path between the dummy and actual data in the stat_tracker_spec! 
Also, sorry, I forgot to uncomment the 'require rspec' at the front of the stat_tracker_spec (I have to comment it out on my local since rspec automatically runs)

### CODE REVIEW

**Review by ashuhleyt — APPROVED** [review]
ooh, thanks naomi!!! This looks great. I am excited to learn more about tally!

**Review by MoxieMax — APPROVED** [review]
Thanks for removing the whitespace

**Review by MoxieMax — APPROVED** [review]
You really put in the work last night, super impressed by your efforts

**Review by kenzjoy — COMMENTED** [review]
Awesome job!

**Comment by kenzjoy** [comment]
merging pull request to continue into League Statistics

**Pull request merged**
